apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  labels:
    app: authentik
    authentik-component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik
      authentik-component: worker
  template:
    metadata:
      labels:
        app: authentik
        authentik-component: worker
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "authentik"
        vault.hashicorp.com/agent-inject-secret-authentik-env: "authentik/data/config"
        vault.hashicorp.com/agent-inject-template-authentik-env: |
          {{- with secret "authentik/data/config" -}}
            export AUTHENTIK_SECRET_KEY="{{ .Data.data.secretKey }}" \n
          {{- end -}}

          {{- with secret "email/data/system" -}}
            export AUTHENTIK_EMAIL__HOST={{ .Data.data.host }}
            export AUTHENTIK_EMAIL__USERNAME={{ .Data.data.username }}
            export AUTHENTIK_EMAIL__PASSWORD="{{ .Data.data.password }}"
            export AUTHENTIK_EMAIL__USE_TLS=true
            export AUTHENTIK_EMAIL__FROM="{{ .Data.data.from }}" \n
          {{- end -}}

          {{- with secret "external/data/maxmind" -}}
            export GEOIPUPDATE_ACCOUNT_ID={{ .Data.data.accountId }}
            export GEOIPUPDATE_LICENSE_KEY={{ .Data.data.licenseKey }} \n
          {{- end -}}

          {{- with secret "keydb/data/config" -}}
            export AUTHENTIK_REDIS__HOST=keydb
            export AUTHENTIK_REDIS__CACHE_DB=4
            export AUTHENTIK_REDIS__MESSAGE_QUEUE_DB=5
            export AUTHENTIK_REDIS__WS_DB=6
            export AUTHENTIK_REDIS__PASSWORD="{{ .Data.data.password }}" \n
          {{- end -}}

          {{- with secret "database/static-creds/authentik" -}}
            export AUTHENTIK_POSTGRESQL__HOST=stolon-proxy
            export AUTHENTIK_POSTGRESQL__NAME=authentik
            export AUTHENTIK_POSTGRESQL__USER=authentik
            export AUTHENTIK_POSTGRESQL__PASSWORD="{{ .Data.password }}" \n
          {{- end -}}
        vault.hashicorp.com/tls-skip-verify: "true"
    spec:
      serviceAccountName: authentik
      containers:
        - name: authentik
          image: ghcr.io/goauthentik/server:2022.4.1
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
            - containerPort: 9443
              name: https
              protocol: TCP
          command:
            - "/bin/bash"
            - "-c"
            - "source /vault/secrets/authentik-env && /lifecycle/ak worker"
