apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
  - apiGroups:
      resources:
        - nodes
        - services
        - pod
    verbs:
      - get
      - watch
      - list
