apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  selector:
    app: transmission
  ports:
    - port: 80
      targetPort: 9091
      name: web-ui
    - port: 51413
      protocol: TCP
      name: tcp-in
    - port: 51413
      protocol: UDP
      name: udp-in
