## Issuer for whole cluster
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca-issuer
spec:
  ca:
    # https://cert-manager.io/docs/configuration/ca/
    secretName: root-ca
