apiVersion: v1
kind: ConfigMap
metadata:
  name: keydb-config
data:
  keydb.conf: |
    ## General
    # Around 75% of 1GiB
    maxmemory 805306368
    databases 20
    port 6379

    ## Multi-master
    # Adding replicas is done in StatefulSet
    active-replica yes
    multi-master yes

    ## Persistence
    # Seconds - Amout of key changes required
    save 900 1
    save 300 10
    save 60 10000
    # Location for dump
    dir /data

    ## TLS
    tls-port 6380
    tls-cert-file /keydb-tls/tls.crt
    tls-key-file /keydb-tls/tls.key
    tls-ca-cert-file /keydb-tls/ca.crt
    tls-replication yes
    tls-cluster yes
    # Do not require certs from clients
    tls-auth-clients optional
