apiVersion: v1
kind: Service
metadata:
  name: keydb
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  selector:
    app: keydb
  ports:
    - protocol: TCP
      port: 6379
      name: redis
    - protocol: TCP
      port: 6380
      name: redis-tls
