## Local storage for KeyDB (Redis replacement)
## Mounts the directory at /mnt/keydb
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-keydb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
## Cypress
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keydb-cypress
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # Don't delete data if PVC is deleted
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-keydb
  local:
    path: /mnt/keydb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cypress
---
## Degray
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keydb-degray
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-keydb
  local:
    path: /mnt/keydb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - degray
---
## Ozarks
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keydb-ozarks
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-keydb
  local:
    path: /mnt/keydb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ozarks
