# https://github.com/villekalliomaki/stolon/blob/master/examples/kubernetes/role.yaml
# Could be split for sentinel/ctl
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stolon
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "events"]
  verbs: ["get", "create", "update", "list", "patch"]