apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloben
  labels:
    app: bloben
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bloben
  template:
    metadata:
      labels:
        app: bloben
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "flame"
        vault.hashicorp.com/agent-inject-secret-env: "flame/config"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "flame/config" -}}
            export PASSWORD={{ .Data.data.password }}
          {{- end -}}
        vault.hashicorp.com/tls-skip-verify: "true"
    spec:
      serviceAccountName: bloben
      containers:
        - name: bloben
          # 
          image: 
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          command: ["/bin/bash", "-c"]
          args:
            - |
              source /vault/secrets/env
              
          livenessProbe:
            exec:
              command: ["curl http://localhost:5232"]
            initialDelaySeconds: 10
            periodSeconds: 10