apiVersion: v1
kind: Service
metadata:
  name: remote-client-wireguard
  labels:
    app: remote-client-wireguard
spec:
  type: NodePort
  selector:
    app: remote-client-wireguard
  ports:
    - port: 51820
      nodePort: 31820
      protocol: UDP
