apiVersion: v1
kind: Service
metadata:
  name: minio
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  selector:
    app: minio
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 9000
    - name: console
      port: 9001
