# Docs for k8s TLS:
# https://github.com/minio/minio/tree/master/docs/tls/kubernetes
# https://github.com/minio/minio/tree/master/docs/tls#3-generate-self-signed-certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
spec:
  secretName: minio-tls
  duration: 720h # 30 days
  renewBefore: 72h # 3 days
  ipAddresses:
    - 127.0.0.1
  dnsNames:
    - minio
    - minio-1disk-0.minio
    - minio-1disk-1.minio
    - minio-2disk-0.minio
    - minio-2disk-0.minio
    - minio-1disk-0.minio.default.svc.cluster.local
    - minio-1disk-1.minio.default.svc.cluster.local
    - minio-2disk-0.minio.default.svc.cluster.local
    - minio-2disk-0.minio.default.svc.cluster.local
  commonName: minio
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
