# https://learn.hashicorp.com/tutorials/vault/kubernetes-raft-deployment-guide?in=vault%2Fkubernetes#configure-vault-helm-chart

global:
  # Enables most components
  enabled: true
  tlsDisable: false

server:
  standalone:
    enable: false
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      # Config under raft key
      # Under HA it doesn't work
      config: |
        ui = true
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/hashicorp-vault-tls/tls.crt"
          tls_key_file = "/vault/userconfig/hashicorp-vault-tls/tls.key"
          tls_ca_cert_file = "/vault/userconfig/hashicorp-vault-tls/ca.crt"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://hashicorp-vault-0.hashicorp-vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/hashicorp-vault-tls/ca.crt"
            leader_client_cert_file = "/vault/userconfig/hashicorp-vault-tls/tls.crt"
            leader_client_key_file = "/vault/userconfig/hashicorp-vault-tls/tls.key"
          }
          retry_join {
            leader_api_addr = "https://hashicorp-vault-1.hashicorp-vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/hashicorp-vault-tls/ca.crt"
            leader_client_cert_file = "/vault/userconfig/hashicorp-vault-tls/tls.crt"
            leader_client_key_file = "/vault/userconfig/hashicorp-vault-tls/tls.key"
          }
          retry_join {
            leader_api_addr = "https://hashicorp-vault-2.hashicorp-vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/hashicorp-vault-tls/ca.crt"
            leader_client_cert_file = "/vault/userconfig/hashicorp-vault-tls/tls.crt"
            leader_client_key_file = "/vault/userconfig/hashicorp-vault-tls/tls.key"
          }

          autopilot {
            cleanup_dead_servers = "true"
            last_contact_threshold = "200ms"
            last_contact_failure_threshold = "10m"
            max_trailing_logs = 250000
            min_quorum = 5
            server_stabilization_time = "10s"
          }
        }

        service_registration "kubernetes" {}
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/hashicorp-vault-tls/ca.crt
  extraVolumes:
    - type: secret
      name: hashicorp-vault-tls
  # PVs must be provisioned before
  # For raft storage
  dataStorage:
    size: 1Gi
    storageClass: local-hashicorp-vault
  # Automatic upgrades after changes
  # wihtout a need to delete pods
  updateStrategyType: RollingUpdate

injector:
  enabled: true
