apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: jackett
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: linuxserver/jackett:version-v0.20.989
          ports:
            # Web
            - containerPort: 9117
              name: web
          env:
            - name: TZ
              value: Europe/Helsinki
          volumeMounts:
            # Config
            - name: jackett
              mountPath: /config
              subPath: config
            # Blackhole
            - name: jackett
              mountPath: /downloads
              subPath: downloads-blackhole
      volumes:
        # Config
        - name: jackett
          persistentVolumeClaim:
            claimName: jackett
