apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-minio
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
# Allow to expand later
allowVolumeExpansion: true
