apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "openldap"
        vault.hashicorp.com/agent-inject-secret-vault.yaml: "openldap/data/config"
        vault.hashicorp.com/agent-inject-template-vault.yaml: |
          {{- with secret "openldap/data/config" -}}
          LDAP_ORGANISATION: {{ .Data.data.organisation }}
          LDAP_DOMAIN: {{ .Data.data.domain }}
          LDAP_BASE_DN: {{ .Data.data.root }}
          LDAP_ADMIN_PASSWORD: {{ .Data.data.adminPassword }}

          {{- end -}}
        # Map to where the env file is loaded from
        vault.hashicorp.com/secret-volume-path: "/container/environment/01-vault"
        vault.hashicorp.com/tls-skip-verify: "true"
    spec:
      serviceAccountName: openldap
      containers:
        - name: openldap
          image: villekalliomaki/openldap:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 389
              name: ldap
              protocol: TCP
            - containerPort: 636
              name: ldaps
              protocol: TCP
          env:
            - name: LDAP_TLS_CRT_FILENAME
              value: tls.crt
            - name: LDAP_TLS_KEY_FILENAME
              value: tls.key
            - name: LDAP_TLS_CA_CRT_FILENAME
              value: ca.crt
            - name: LDAP_TLS_VERIFY_CLIENT
              value: never
            - name: DISABLE_CHOWN
              value: "true"
          volumeMounts:
            # TLS
            - mountPath: /container/service/slapd/assets/certs/tls.crt
              subPath: tls.crt
              name: openldap-tls
              readOnly: true
            - mountPath: /container/service/slapd/assets/certs/tls.key
              subPath: tls.key
              name: openldap-tls
              readOnly: true
            - mountPath: /container/service/slapd/assets/certs/ca.crt
              subPath: ca.crt
              name: openldap-tls
              readOnly: true
            # Data
            - name: openldap
              mountPath: /var/lib/ldap
              subPath: ldap
            - name: openldap
              mountPath: /etc/ldap/slapd.d
              subPath: slapd.d
      volumes:
        - name: openldap
          persistentVolumeClaim:
            claimName: openldap
        - name: openldap-tls
          secret:
            secretName: openldap-tls
