apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  selector:
    app: openldap
  ports:
    - port: 389
      name: ldap
      protocol: TCP
    - port: 636
      name: ldaps
      protocol: TCP
