apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-tls
spec:
  secretName: openldap-tls
  duration: 720h # 30 days
  renewBefore: 72h # 3 days
  ipAddresses:
    - 127.0.0.1
  dnsNames:
    - openldap
  commonName: openldap
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
