apiVersion: v1
kind: Service
metadata:
  name: stolon-keeper
spec:
  clusterIP: None
  selector:
    component: stolon-keeper
    stolon-cluster: stolon-prod
  ports:
    - port: 5432
      protocol: TCP
