apiVersion: apps/v1
kind: Deployment
metadata:
  name: flame
  labels:
    app: flame
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flame
  template:
    metadata:
      labels:
        app: flame
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "flame"
        vault.hashicorp.com/agent-inject-secret-pwd: "flame/config"
        vault.hashicorp.com/agent-inject-template-pwd: |
          {{- with secret "flame/config" -}}
            export PASSWORD={{ .Data.data.password }}
          {{- end -}}
        vault.hashicorp.com/tls-skip-verify: "true"
    spec:
      serviceAccountName: flame
      containers:
        - name: flame
          image: pawelmalak/flame:multiarch2.3.0
          ports:
            - containerPort: 5005
              name: http
          command:
            - "/bin/sh"
            - "-c"
            - "source /vault/secrets/pwd && chown -R node /app/data && node server.js"
          volumeMounts:
            - name: flame
              mountPath: /app/data
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 30Mi
              cpu: 80m
      volumes:
        - name: flame
          persistentVolumeClaim:
            claimName: flame
