apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
data:
  settings.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv"
    }
